### ISSUE TITLE
Search function and clean gui

### ISSUE THREAD

**Issue by RennyDemmy** [voncloft/VPacman#1]
Dear Voncloft,

Not really an issue, but I thought it would be useful if you add a search function and maybe a cleaner GUI like Pamac. Hope you have a great day!

Regards,

**Comment by voncloft** [comment]
There is a search textbox in the top right of the application, as for the cleaner gui can you be a bit more precise on the matter?

Thanks

**Comment by RennyDemmy** [comment]
Well, for the latter, what I meant was something more organized like Pamac or Synaptic or even GNOME Software (which does look a bit complicated, but I just wanted to give an example).

**Comment by voncloft** [comment]
I'll keep that in mind, I sort of did this to venture out as my "first" Qt Project lol.....wanted to see if I could do it. I just like to tinker with the project when I get bored. But if and when I get back to it I will definately do more with it.

**Comment by RennyDem** [comment]
If I knew how to do it, I'd probably give you a hand too.

**Comment by RennyDemmy** [comment]
But thanks for everything!

**Comment by voncloft** [comment]
sure I sign on "occasionally" but if you'd like - Linuxking#1934

**Comment by RennyDem** [comment]
Added!
